name: Gemini AI Code Reviewer

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/gemini-review')
    steps:
      - name: Display PR Info
        run: |
          echo "Triggered by Comment: ${{ github.event.comment.body }}"
          echo "PR Number: ${{ github.event.issue.number }}"
          echo "Repo: ${{ github.repository }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch PR Details
        id: pr-details
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_json=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          echo "head_sha=$(echo $pr_json | jq -r .head.sha)" >> $GITHUB_OUTPUT
          echo "base_sha=$(echo $pr_json | jq -r .base.sha)" >> $GITHUB_OUTPUT

      - name: Gemini AI Code Review
        uses: truongnh1992/gemini-ai-code-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-1.5-pro-002
          INPUT_EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
